[package]
name = "ro-bura/xclass"
description = "just class module for me"

version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

authors = ["RO_BURa"]
license = "MIT"

include = ["src/", "src/**", "Packages", "Packages/**", "bin", "bin/**", "default.project.json", "place.project.json", "wally.toml", "selene.toml"]
exclude = ["**"]

[dependencies]
TuplePacker = "ro-bura/tuplepacker@0.1.2"
NoYield = "ro-bura/noyield@0.1.2"
ArgsUtils = "ro-bura/argsutils@0.1.1"